### ISSUE TITLE
Compass disappear

### ISSUE THREAD

**Issue by minhh2792** [MherZaqaryan/Bedwars1058-Compass#1]
I can't speak English so I can't describe it here, you can watch this video https://www.youtube.com/watch?v=dnd2WHVYJAM

**Comment by minhh2792** [comment]
I don't want player to move any item to the menu, because it just gonna disappear

**Comment by MherZaqaryan** [comment]
Hey, thank you should be fixed in the next update!

**Comment by MherZaqaryan** [comment]
This issue is fixed, download it from here: https://www.spigotmc.org/resources/addon-bedwars1058-compass-team-tracker-quick-communications-multi-language-support.91537/
Thanks again!
