### ISSUE TITLE
Tracker shop GUI make NullPointerException

### ISSUE THREAD

**Issue by SiriHackYT** [MherZaqaryan/Bedwars1058-Compass#7]
![image](https://user-images.githubusercontent.com/49961233/155888669-3312b2e8-9f8c-4283-a116-130cd671b070.png)

When i click on the menu with the compass ingame and if i click on the "Tracker Shop" this error print on the console

**Comment by MherZaqaryan** [comment]
This issue has been fixed and will be available in the next update!
